#!/bin/bash

# Default values
reload=false
wallpaperPath=~/.config/hypr/wallpaper
sddmPath=/usr/share/sddm/themes/sugar-candy/Backgrounds/Wallpaper.png

# Display help message
display_help() {
  echo "
  Usage: $0 [-r] <filename>
  Set a new wallpaper on the system using the swww command.

  Options:
  -r          Reload the current wallpaper
  -h          Display this help message

  Arguments:
  <filename>  Path to the image file to set as the wallpaper

  Default Values:
  Wallpaper Path: $wallpaperPath
  SDDM Wallpaper Path: $sddmPath

  Examples:
  $0 -r        # Reload the current wallpaper
  $0 image.jpg # Set 'image.jpg' as the new wallpaper
  "
}

if [ "$#" -eq 0 ] || [ "$1" == "--help" ] ; then
  display_help
  exit 1
fi

  while getopts ":rh" opt; do
  case ${opt} in
    r) reload=true ;;
    h) display_help; exit 0 ;;
    \?) echo "Invalid option: -$OPTARG" >&2; exit 1 ;;
  esac
done

# Shift command line arguments to get the filename
shift $((OPTIND - 1))

# Check if file exists
filename=$(readlink -f "${1:-}")
if [ ! -f "$filename" ] && [ $reload = false ]; then
  echo "File not found."
  exit 1
fi

# Reload or set new wallpaper
if [ "$reload" = true ]; then
  swww img "$wallpaperPath"  --transition-type any
  action="reloaded"
else
  cp "$filename" "$wallpaperPath" && action="loaded: "
  swww img "$wallpaperPath" --transition-type any
fi

echo "Wallpaper $action$filename"
